### ISSUE TITLE
Inhalte / Todo

### ISSUE THREAD

**Issue by ahocevar** [ahocevar/fossgis2022-openlayers#1]
@marcjansen Hier mein Vorschlag zu Inhalten und die dazu nötigen Schritte:

### Meta

Bereits genug Inhalt.

- [ ] @marcjansen Wenn geht nur 1 statt 2 Slides zur Vorstellung; Hiring eventuell raus?
- [x] @ahocevar Neue Slides Grundkonzepte, Anwendungsbereiche und Historisches

### Beispiele

- [x] Modify Interaction für Polygone mit 100.000 Vertices (aus Fractals Example)
- [x] Multisource Layer (GeoTIFF Pyramid)
- [x] WebGL Data Tiles (Sea level)
- [x] `MapboxVector` Layer
- [x] `setUserProjection`, proj4 Integration (Alternative zu Reprojection)
- [x] Minimal Map mit Layerswitcher, Marker und Popup (3rd party, `setUserProjection()`)

### Ausblick

- Rich Text Labels
- Mehr Worker, mehr WebGL => schnellere Renderer
- Support für Aspekte von OGC API Features, STAC

**Comment by ahocevar** [comment]
@marcjansen Bitte gerne ergänzen und ev. deinen Namen dazuschreiben, wenn du was davon machen möchtest.

Zeitrahmen ist ja relativ eng, ich habe vor bis 8. oder 9.2. mit meinem Teil der Slides fertig zu sein.
